services:
  hysteria2-v2bx:
    image: fireinrain/hysteria2-v2bx:latest
    container_name: hysteria2-v2bx
    restart: unless-stopped
    network_mode: host
    environment:
      - apiHost=${apiHost}
      - apiKey=${apiKey}
      - nodeID=${nodeID}
    # 如果需要自定义配置和设置证书，请挂载配置目录
    #volumes:
    #  - ./config:/etc/hysteria
