#!/bin/sh

CONFIG_FILE="/etc/hysteria/server.yaml"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Creating configuration file $CONFIG_FILE"
    mkdir -p /etc/hysteria
    cat <<EOF >"$CONFIG_FILE"
listen: :443

v2board:
  apiHost: ${apiHost}
  apiKey: ${apiKey}
  nodeID: ${nodeID}

acme:
  domains:
    - ${domain}
  email: ${email:-your@email.com}

auth:
  type: v2board

trafficStats:
  listen: 127.0.0.1:7653

# 如果需要设置warp路由，需要注释掉outbounds配置，并且在acl中添加warp路由规则
#outbounds:
# # 指定 SOCKS5
# - name: proxy
#   type: socks5
#   socks5:
#     addr: 127.0.0.1:40000

acl:
  inline:
    - reject(10.0.0.0/8)
    - reject(172.16.0.0/12)
    - reject(192.168.0.0/16)
    - reject(127.0.0.0/8)
    - reject(fc00::/7)
#    - proxy(geosite:google)
#    - proxy(geoip:google)
EOF
fi

hysteria server -c "$CONFIG_FILE" 2>&1 | tee &

HYSTERIA_PID=$!

cleanup() {
    echo "Received stop signal, shutting down hysteria..."
    kill -SIGINT "$HYSTERIA_PID" 2>/dev/null
    wait "$HYSTERIA_PID"
    exit 0
}

trap cleanup INT
trap cleanup TERM

wait