name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26"

      - name: Build core
        working-directory: core
        run: go build ./...

      - name: Build extras
        working-directory: extras
        run: go build ./...

      - name: Build app
        working-directory: app
        run: go build ./...